services:
  bilibili_tool:
    image: ghcr.io/raywangqvq/bilibili_tool_web
    container_name: bili
    restart: unless-stopped
    tty: true
    volumes:
      - ./Logs:/app/Logs
    ports:
      - 22333:8080
    environment:
      - Ray_DailyTaskConfig__Cron="0 0 15 * * ?"
