name: Publish My Docker Image

on:
  workflow_dispatch:  # 允许手动触发
  push:
    tags:
      - '*'  # 当推送标签时触发

env:
  GHCR_USERNAME: ${{ github.repository_owner }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GHC_IMG_NAME: "ghcr.io/10000ge10000/bili_tool_web"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        id: getVersion
        run: |
          VERSION=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' ./common.props)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GHC_IMG_NAME }}:${{ steps.getVersion.outputs.VERSION }}
            ${{ env.GHC_IMG_NAME }}:latest
